### ISSUE TITLE
📦 AWS Deployment for Spring Boot + PostgreSQL Backend

### ISSUE THREAD

**Issue by jomariabejo** [jomariabejo/connectly-api#1]
This guide provides a comprehensive step-by-step approach to deploy Spring Boot + PostgreSQL backend application on AWS with a CI/CD pipeline using GitHub Actions.

---

### 1.1 VPC and Networking
1. **Create a new VPC** in the AWS Console.
2. Set up:
   - **Public subnets** for load balancer or EC2 (if needed)
   - **Private subnets** for RDS
3. Configure:
   - **Internet Gateway** and attach to the VPC
   - **Route tables** to enable public subnet internet access
   - **Security Groups**
     - Allow HTTP/HTTPS for your app
     - Allow port **5432** from the app to PostgreSQL

### 1.2 RDS (PostgreSQL Database)
1. Navigate to **Amazon RDS** > Create database
2. Choose **PostgreSQL**
3. Recommended settings:
   - **DB Instance Class**: db.t3.micro (for testing)
   - **Multi-AZ**: Disable (for dev/testing)
   - **Public Access**: No (keep private)
   - **VPC**: Use the one created earlier
   - **Credentials**: Set master username/password (store safely)
4. Configure **security group** to allow inbound access from app’s security group

---

## 🚀 2. Application Deployment Options

Choose one of the following methods to deploy the Spring Boot app:

#### 2A.1 Prepare Your App
Add a `Dockerfile` to your project:
```dockerfile
FROM openjdk:17
VOLUME /tmp
COPY target/your-app.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
```

#### 2A.2 Build and Push Docker Image
Create Amazon ECR repository:
```bash
aws ecr create-repository --repository-name your-app-repo
```
Authenticate and push:
```bash
aws ecr get-login-password --region <region> | docker login --username AWS --password-stdin <aws_account_id>.dkr.ecr.<region>.amazonaws.com

docker build -t your-app .
docker tag your-app:latest <repo_uri>:latest
docker push <repo_uri>:latest
```

#### 2A.3 EC2 Setup
Launch **EC2 instance** (Amazon Linux 2)

SSH into instance:
```bash
ssh -i your-key.pem ec2-user@your-ec2-ip
```
Install Docker:
```bash
sudo yum update -y
sudo amazon-linux-extras install docker
sudo service docker start
sudo usermod -a -G docker ec2-user
```
Pull and run your container:
```bash
docker pull <repo_uri>:latest
docker run -d -p 80:8080 <repo_uri>:latest
```

### Option B: Elastic Beanstalk (Simpler, managed)
1. Package your Spring Boot app as a `.jar` file
2. Install [[EB CLI](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install.html)](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli3-install.html)
3. Initialize and deploy:
```bash
eb init -p java your-app-name
eb create your-env-name
eb deploy
```

### Option C: ECS (Fargate)
1. Push Docker image to ECR (as in 2A.2)
2. Create ECS task definition
3. Create service and cluster
4. Connect with RDS in same VPC
5. Use ALB for traffic routing

---

### 3.1 GitHub Secrets
In your repository, add the following secrets:
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`
- `ECR_REPOSITORY_URI`
- `AWS_REGION`
- `EC2_HOST`, `EC2_USER`, `EC2_KEY` (if using EC2 and SSH deploy)

### 3.2 Sample GitHub Actions Workflow
```yaml
name: Deploy to AWS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Login to Amazon ECR
      run: |
        echo "${{ secrets.AWS_SECRET_ACCESS_KEY }}" | docker login -u AWS --password-stdin ${{ secrets.ECR_REPOSITORY_URI }}

    - name: Build and Push Docker Image
      run: |
        docker build -t app .
        docker tag app:latest ${{ secrets.ECR_REPOSITORY_URI }}:latest
        docker push ${{ secrets.ECR_REPOSITORY_URI }}:latest

    - name: Deploy via SSH (EC2 Example)
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          docker pull ${{ secrets.ECR_REPOSITORY_URI }}:latest
          docker stop app || true && docker rm app || true
          docker run -d -p 80:8080 --name app ${{ secrets.ECR_REPOSITORY_URI }}:latest
```

---

## 📊 4. Monitoring and Scaling
- Use **CloudWatch Logs** for real-time log analysis
- Create **Alarms** for CPU/Memory/Latency
- Set up **Auto Scaling Groups** for EC2 (optional)
- Enable **Health Checks** (ALB or EC2 status checks)

---

## 🔐 5. Secure Configuration
- Store sensitive config in **AWS Systems Manager Parameter Store** or **Secrets Manager**
- In Spring Boot, read them using environment variables or AWS SDK

---

## ✅ Final Checklist
- [ ] RDS database setup with correct VPC/Security Group
- [ ] Dockerized Spring Boot application
- [ ] Deployed app (EC2 / Beanstalk / ECS)
- [ ] CI/CD pipeline on GitHub Actions
- [ ] Environment variables and secrets managed securely
- [ ] Logs and metrics configured in CloudWatch
